### ISSUE TITLE
preprocessing of omics data

### ISSUE THREAD

**Issue by ks2022ml** [luyiyun/MCluster-VAEs#1]
Hi 

is it possible to provide more guidance on how the data files from UCSC's PanCan
https://xenabrowser.net/datapages/?cohort=GDC%20Pan-Cancer%20(PANCAN)&removeHub=https%3A%2F%2Fxena.treehouse.gi.ucsc.edu%3A443

are processed into the files used for the mcluster, i.e.
            "./data/pancancer/fea/meth.fea",
            "./data/pancancer/fea/rna.fea",
            "./data/pancancer/fea/CN.fea",
            "./data/pancancer/fea/miRNA.fea"

Thank you.

**Comment by luyiyun** [comment]
the following comes from the manuscript of MCluster-VAEs:

We then preprocessed this dataset using a 6-steps approach: 
1. to filter samples to ensure that they exist in all four omics; 
2. to perform log transformation of mRNA and miRNA; 
3. to remove duplicated regions data of CNA and convert it into gene-level form; 
4. to select the features using Yang’s approaches (Yang et al., 2021), retaining 3105 CNA features, 3217 mRNA features, 383 miRNA features and 3139 methylation features (threshold by variance); 
5. to perform missing data imputation by the samples’ mean value; 
6. To standardize features in each omics by removing the mean and scaling the feature to unit variance.

**Comment by ks2022ml** [comment]
Thank you for the info.

Would it be possible to provide the .fea files so I can check if we can get the same datafiles after doing what you described?

**Comment by luyiyun** [comment]
The .fea files are included in release, and you can download them yourself.

**Comment by ks2022ml** [comment]
sorry when would be the release be available? thank you.

**Comment by luyiyun** [comment]
I mean the "Releases" part of github. : )
![image](https://user-images.githubusercontent.com/37055697/173243525-c7fe2455-1724-4dac-b0d9-7ffdada5ea4f.png)

**Comment by ks2022ml** [comment]
ha! sorry i didnt realise that and thank you!
